# Generated by Django 5.2.7 on 2025-11-18 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contributions_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributions',
            name='created_by',
        ),
        migrations.AddField(
            model_name='contributions',
            name='targeted_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='targeted_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributors',
            name='payment_method',
            field=models.CharField(choices=[('N', 'Normal Payments'), ('P', 'Mobile Phone Payments'), ('B', 'Bank Payments')], default='N', max_length=5),
        ),
        migrations.AddField(
            model_name='contributors',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_create', to=settings.AUTH_USER_MODEL),
        ),
    ]
