# Generated by Django 5.2.7 on 2025-11-20 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_contributions_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributors',
            name='price',
        ),
        migrations.AddField(
            model_name='contributors',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='Contributions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='api.contributions'),
        ),
    ]
